import {
  Baby,
  Book,
  Briefcase,
  Car,
  CirclePlay,
  Dog,
  Gift,
  Heart,
  House,
  Palette,
  Pill,
  Plane,
  Plug,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  User,
  Users,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

export const ICON_NAMES = [
  'utensils',
  'house',
  'circle-play',
  'users',
  'user',
  'gift',
  'car',
  'plane',
  'shopping-cart',
  'shopping-bag',
  'briefcase',
  'book',
  'plug',
  'smartphone',
  'sparkles',
  'heart',
  'baby',
  'dog',
  'pill',
  'scissors',
  'palette',
  'wallet',
] as const

export type IconName = (typeof ICON_NAMES)[number]

const map: Record<string, LucideIcon> = {
  utensils: Utensils,
  house: House,
  'circle-play': CirclePlay,
  users: Users,
  user: User,
  gift: Gift,
  car: Car,
  plane: Plane,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  briefcase: Briefcase,
  book: Book,
  plug: Plug,
  smartphone: Smartphone,
  sparkles: Sparkles,
  heart: Heart,
  baby: Baby,
  dog: Dog,
  pill: Pill,
  scissors: Scissors,
  palette: Palette,
  wallet: Wallet,
}

export function getIcon(name: string): LucideIcon {
  return map[name] ?? User
}
